name: Release app
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", " windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run make
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GHPROJECT_TOKEN }}
        run: npm run publish
